version: "3.7"

services:
  app:
    image: gcr.io/gke-test-287910/folks:v0.0.2
    ports:
      - "8000:8000"
    environment:
      AP_PORT: 8000
      MQ_HOST: nats
      MQ_PORT: 4222
    depends_on:
      - nginx
      - nats
    volumes:
      - ./app/data:/srv
  nginx:
    image: gcr.io/gke-test-287910/folks-nginx:v0.0.1
    ports:
      - "80:80"
    volumes:
      - ./nginx/index.html:/var/www/static/index.html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  nats:
    image: nats:latest # NATS JetStreamも検討
    ports:
      - "4222:4222"