version: "3.7"

services:
  app:
    image: gcr.io/gke-test-287910/folks:v0.0.6
    ports:
      - "8000:8000"
    environment:
      AP_PORT: 8000
      MQ_HOST: nats
      MQ_PORT: 4222
      KVS_PASSWORD: password
      KVS_HOST: redis
      KVS_DATABASE: 0
      KVS_PORT: 6379
      DB_PASSWORD: password
      DB_HOST: mysql
      DB_DATABASE: folks
      DB_PORT: 3306
    depends_on:
      - nginx
      - nats
    volumes:
      - ./app/data:/srv
  nginx:
    image: gcr.io/gke-test-287910/folks-nginx:v0.0.1
    ports:
      - "80:80"
    volumes:
      - ./nginx/roomSelect/index.html:/var/www/static/index.html
      - ./nginx/chatRoom/index.html:/var/www/room/index.html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  nats:
    image: nats:latest # NATS JetStreamも検討
    ports:
      - "4222:4222"
  redis:
    image: redis:latest
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    platform: linux/amd64
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: folks