version: "3.7"

services:
  nginx:
    # image: gcr.io/gke-test-287910/folks-nginx:v0.0.1
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/index.html:/var/www/static/index.html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  nats:
    image: nats:latest # NATS JetStreamも検討
    ports:
      # - "8222:8222"
      - "4222:4222"